lab1c/website/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path

from checkout import views


urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
]

lab1c/checkout/models.py
from django.db import models

class Status(models.Model):
    description = models.TextField()
    created_at  = models.DateTimeField()
    updated_at  = models.DateTimeField()
    class Meta:
        db_table = "status"

    def __str__(self):
        return self.description

class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=128)
    created_at  = models.DateTimeField()
    updated_at  = models.DateTimeField()
    signed_agreement = models.BooleanField()
    class Meta:
        db_table = "users"

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Inventory(models.Model):
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    description = models.TextField()
    created_at  = models.DateTimeField()
    updated_at  = models.DateTimeField()
    class Meta:
        db_table = "inventory"

    def __str__(self):
        return self.description

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    checkout_time = models.DateTimeField()
    scheduled_checkin_time = models.DateTimeField()
    actual_checkin_time = models.DateTimeField()
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    class Meta:
        db_table = "transactions"
    
    def __str__(self):
        return 'user ' + self.user + '\nchecked out ' + self.inventory + '\nat ' + self.checkout_time 

lab1c/checkout/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404

from .models import User
from .models import Transaction

def home(request):
    user =  User.objects.get(id="1")
    transactions =  Transaction.objects.filter(checkout_time__lt='2018-09-03')
    return render(request, 'home.html', {'user': user, 'transactions': transactions})

lab1c/checkout/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CSC561 | Lab1c</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  </head>
<body>

<h3>All items that user1 has checked out with the corresponding checkout_time</h3>

<table border="1" cellpadding="5px" cellspacing="0">
                                <thead>
          <th>Inventory Item</th>
          <th>Checkout Time</th>
                                </thead>

        <tbody>
        {% for transaction in user.transaction_set.all %}
            <tr>
		<td>{{ transaction.inventory.description }}</td>
		<td>{{ transaction.checkout_time }}</td>
            </tr>
        {% endfor %}
        </tbody>
</table>

<h3>All users who checked out items before September 3 2018.  Show user first name, the item description, checkout_time and the status</h3>

<table border="1" cellpadding="5px" cellspacing="0">
                                <thead>
          <th>User's first name</th>
          <th>Item Description</th>
          <th>Checkout time</th>
          <th>Status</th>
                                </thead>

                                <tbody>
        {% for transaction in transactions %}
            <tr>

                <td>{{ transaction.user.first_name }}</td>
		<td>{{ transaction.inventory.description }}</td>
                <td>{{ transaction.checkout_time }}</td>
		<td>{{ transaction.inventory.status.description }}</td>

            </tr>
        {% endfor %}
        </tbody>
</table>

</body>
</html>